###
GET http://localhost:3000/style/curations

###
GET http://localhost:3000/style/curations?searchBy=nickname&keyword=잠만보&page=1&pageSize=2
###
GET http://localhost:3000/style/curations?&page=1&pageSize=5

###
POST http://localhost:3000/style/curations
Content-Type: application/json

{
  "nickname": "라이츄",
  "passwd": "qwe12345",
  "content": "별로에요",
  "trendy": 5,
  "practicality":3,
  "costEffectiveness":2
}

###
PUT http://localhost:3000/style/curations/2
Content-Type: application/json

{
  "nickname": "잠만보",
  "passwd": "qwe1234",
  "content": "가성비가 나쁘지는 않아요",
  "trendy": 7,
  "personality": 7,
  "practicality":7,
  "costEffectiveness":7
}
###
DELETE http://localhost:3000/style/curations/7